# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(nom: 'Agon', prenom: 'Armand', mail:'Agon.Armand@gmail.com')
User.create(nom: 'Boulanger', prenom: 'Benoit', mail:'Boulanger.Benoit@gmail.com')
User.create(nom: 'Cule', prenom: 'Cécile', mail:'Cule.Cécile@gmail.com')
User.create(nom: 'Dubois', prenom: 'Dorient', mail:'Dubois.Dorient@gmail.com')
User.create(nom: 'Emen', prenom: 'Edward', mail:'Emen.Edward@gmail.com')
User.create(nom: 'Figarot', prenom: 'Florent', mail:'Figarot.Florent@gmail.com')
User.create(nom: 'Gile', prenom: 'Gautier', mail:'Gile.Gautier@gmail.com')
User.create(nom: 'Hans', prenom: 'Hans', mail:'Hans.Hans@gmail.com')
User.create(nom: 'Ialesyeuxbleu', prenom: 'Isabelle', mail:'Ialesyeuxbleu.Isabelle@gmail.com')
User.create(nom: 'Joestars', prenom: 'Joe', mail:'Joestars.Joe@gmail.com')
User.create(nom: 'Kent', prenom: 'Kevin', mail:'Kent.Kilian@gmail.com')
User.create(nom: 'Renkins', prenom: 'Richard', mail:'Renkins.Richard@gmail.com')

Projet.create(sujet: 'Test01', description: 'Test 01', date_rendu: '2015-07-31')
Projet.create(sujet: 'Test02', description: 'Test 02', date_rendu: '2015-07-31')

ProjetToUserLink.create(projet_id: 1, user_id: 11)
ProjetToUserLink.create(projet_id: 1, user_id: 12)
ProjetToUserLink.create(projet_id: 2, user_id: 12)

Rendu.create(note: 1, projet_id: 1)
Rendu.create(note: 2, projet_id: 1)
Rendu.create(note: 3, projet_id: 1)
Rendu.create(note: 4, projet_id: 1)
Rendu.create(note: 5, projet_id: 1)
Rendu.create(note: 6, projet_id: 1)
Rendu.create(note: 7, projet_id: 1)
Rendu.create(note: 8, projet_id: 1)
Rendu.create(note: 9, projet_id: 1)
Rendu.create(note: 10, projet_id: 1)
Rendu.create(note: 11, projet_id: 2)
Rendu.create(note: 12, projet_id: 2)
Rendu.create(note: 13, projet_id: 2)
Rendu.create(note: 14, projet_id: 2)
Rendu.create(note: 15, projet_id: 2)
Rendu.create(note: 16, projet_id: 2)
Rendu.create(note: 17, projet_id: 2)
Rendu.create(note: 18, projet_id: 2)
Rendu.create(note: 19, projet_id: 2)
Rendu.create(note: 20, projet_id: 2)

RenduToUserLink.create(rendu_id: 1,user_id: 1)
RenduToUserLink.create(rendu_id: 2,user_id: 2)
RenduToUserLink.create(rendu_id: 3,user_id: 3)
RenduToUserLink.create(rendu_id: 4,user_id: 4)
RenduToUserLink.create(rendu_id: 5,user_id: 5)
RenduToUserLink.create(rendu_id: 6,user_id: 6)
RenduToUserLink.create(rendu_id: 7,user_id: 7)
RenduToUserLink.create(rendu_id: 8,user_id: 8)
RenduToUserLink.create(rendu_id: 9,user_id: 9)
RenduToUserLink.create(rendu_id: 10,user_id: 10)
RenduToUserLink.create(rendu_id: 11,user_id: 1)
RenduToUserLink.create(rendu_id: 12,user_id: 2)
RenduToUserLink.create(rendu_id: 13,user_id: 3)
RenduToUserLink.create(rendu_id: 14,user_id: 4)
RenduToUserLink.create(rendu_id: 15,user_id: 5)
RenduToUserLink.create(rendu_id: 16,user_id: 6)
RenduToUserLink.create(rendu_id: 17,user_id: 7)
RenduToUserLink.create(rendu_id: 18,user_id: 8)
RenduToUserLink.create(rendu_id: 19,user_id: 9)
RenduToUserLink.create(rendu_id: 20,user_id: 10)
RenduToUserLink.create(rendu_id: 1,user_id: 3)
RenduToUserLink.create(rendu_id: 2,user_id: 4)
RenduToUserLink.create(rendu_id: 3,user_id: 5)
RenduToUserLink.create(rendu_id: 4,user_id: 6)
RenduToUserLink.create(rendu_id: 5,user_id: 7)
RenduToUserLink.create(rendu_id: 6,user_id: 8)
RenduToUserLink.create(rendu_id: 7,user_id: 9)
RenduToUserLink.create(rendu_id: 8,user_id: 10)
RenduToUserLink.create(rendu_id: 9,user_id: 1)
RenduToUserLink.create(rendu_id: 10,user_id: 2)